version: '3.9'

services:
  postgresql:
    image: postgres:17.2-alpine3.20
    container_name: postgrsql-v17-2
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gemini
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - connection-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 5s
      retries: 10

networks:
  connection-network:
    driver: bridge

volumes:
  db: